### ISSUE TITLE
How to provide `path` input?

### ISSUE THREAD

**Issue by rajat1saxena** [withastro/action#13]
My Astro site is located in the `apps/docs` directory of my project (a monorepo) and following is my deployment action file.

```
name: Deploy documentation

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:
    inputs:
      path:
        description: 'Path to your Astro project'
        required: true
        default: './apps/docs'
        type: string
  
# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v2          
      - name: Install, build, and upload your site
        uses: withastro/action@v0

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
```

The workflow is not running inside the specified folder i.e. `apps/docs`. What is the problem?

**Comment by mandar1jn** [comment]
Hi. The Astro/action action takes an input named path that should point to your root folder. Like this: indentation might be wrong since I am on mobile
```yaml

name: Deploy documentation

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:
    inputs:
      path:
        description: 'Path to your Astro project'
        required: true
        default: './apps/docs'
        type: string
  
# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v2          
      - name: Install, build, and upload your site
        uses: withastro/action@v0
        with:
            path: PATH_TO_ROOT

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
```
