### ISSUE TITLE
Add Support for setting CLI Flags

### ISSUE THREAD

**Issue by abegehr** [withastro/action#42]
It would be great to have an option to set cli flags on the `astro build` command.
Specifically, I'd like to specify the `--config` flag to deploy a static version of my site.

**Comment by natemoo-re** [comment]
I like the idea but it might be better solved by an environment variable? That would require an upstream change to `astro` to support something like `ASTRO_CONFIG_PATH` as well as `--config`. That would be more secure than allowing an arbitrary string to be executed (which could potentially allow an attacker to exfiltrate private tokens via PR.)

**Comment by delucis** [comment]
As of #49 and v4.2.0 of the action there’s a `build-cmd` input to the action to allow for customisation of the build command, including adding flags if needed:

```yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: withastro/action@v4
        with:
            build-cmd: pnpm run build --config custom.config.mjs
```
