### ISSUE TITLE
env.VERSION Not Initialized When Using pnpm in GitHub Actions

### ISSUE THREAD

**Issue by matteo-cavallo** [withastro/action#69]
When using pnpm as the package manager in a GitHub Action workflow, the environment variable env.VERSION is not properly initialized. This results in the following step failing:

```yaml
- name: Setup PNPM
  if: ${{ env.PACKAGE_MANAGER == 'pnpm' }}
  uses: pnpm/action-setup@v4
  with:
    version: ${{ env.VERSION }}
    package_json_file: "${{ inputs.path }}/package.json"
``` 

Since env.VERSION is not set, the pnpm/action-setup step does not function correctly.

**Potential Cause**

The issue appears to stem from the package manager detection logic:
```yaml
elif [ $(find "." -maxdepth 1 -name "pnpm-lock.yaml") ]; then
    echo "PACKAGE_MANAGER=pnpm" >> $GITHUB_ENV
    echo "LOCKFILE=pnpm-lock.yaml" >> $GITHUB_ENV
```
While PACKAGE_MANAGER and LOCKFILE are being assigned, VERSION is not explicitly set, causing workflows that rely on it to break.
