### ISSUE TITLE
Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved

### ISSUE THREAD

**Issue by hyperknot** [withastro/action#70]
I'm using the official file on the website. It used to work, but recently GitHub terminates it with this error:

```
#[error]Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
```

I'm using pnpm. I think it's related how this action sets up node and it's package manager internally, I guess it uses `actions/setup-node@v4`.

**Comment by hyperknot** [comment]
I looked into it, both yarn and pnpm is broken.

The only way to make it work at the moment is to specify npm like this:

```
        uses: withastro/action@v3
        with:
          path: website
          package-manager: npm@latest
```

Of course this means that the locked versions are not read, but it's probably not too much of a problem for simple, GitHub hosted Astro sites.
