### ISSUE TITLE
Does not work properly with starlight + custom domain

### ISSUE THREAD

**Issue by Robin-Sch** [withastro/action#79]
https://github.com/pokehunt-xyz/documentation

```
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v4

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

Whenever I don't have configuration a custom domain in github pages and go to https://pokehunt-xyz.github.io/documentation/ it works (although CSS fails to load because the base is wrong). If I set the custom domain to `docs.pokehunt.xyz` I get `404 page not found` (not even the custom 404 page, which should be loaded?).

Any help would be appreciated
