### ISSUE TITLE
Enable running action without a lock file

### ISSUE THREAD

**Issue by torn4dom4n** [withastro/action#8]
Hi, I tried to use this action with [my repo](https://github.com/AREA44/astro-firstweb). And I see it doesn't run if my repo doesn't have a lock file. Please enable running this action without a lockfile.

**Comment by mandar1jn** [comment]
I believe that you can specify a package manager to use when no lock file is found using the `package-manager` input

**Comment by mandar1jn** [comment]
As I said, I believe you can. After node-version, specify package-manager: PACKAGE-MANAGER. It’s mentioned in the readme of this repo too

**Comment by natemoo-re** [comment]
Thanks @mandar1jn and @torn4dom4n! For any future visitors, the following will work without a lockfile. You just need to specify `with.package-manager: npm | yarn | pnpm`.

```yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v2          
      - name: Install, build, and upload your site output
        uses: withastro/action@v0
        with:
            package-manager: npm
```
